stages:
  - build
  - deploy

variables:
  MKDOCS_BUILD_DIR: public

build_site:
  stage: build
  image: python:3.9
  script:
    - pip install mkdocs
    - mkdocs build --site-dir $MKDOCS_BUILD_DIR
  artifacts:
    paths:
      - $MKDOCS_BUILD_DIR

deploy_pages:
  stage: deploy
  script:
    - mv $MKDOCS_BUILD_DIR public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main